import { HttpConfiguration } from '../types/HttpConfiguration';
import { HttpResponse } from '../types/HttpResponse';
import { Resource } from '../types/Resource';
import { CreateResourceOptions } from '../types/CreateResourceOptions';
import { HTTPError } from '../error/HTTPError';
import { FetchResourceOptions } from '../types/FetchResourceOptions';
export declare class ActuatorResource implements Resource {
    private appCtx;
    private status;
    get idle(): boolean;
    get pending(): boolean;
    get success(): boolean;
    get failure(): boolean;
    get completed(): boolean;
    uploadProgress: number;
    downloadProgress: number;
    private _response;
    get response(): HttpResponse | undefined;
    private _error;
    get error(): HTTPError | undefined;
    private configuration;
    private createResourceOptions;
    private stopTrigger;
    private responseDefer;
    get responsePromise(): Promise<HttpResponse>;
    init(configuration: HttpConfiguration, createResourceOptions: CreateResourceOptions): void;
    onCleanup(): void;
    fetch(options: FetchResourceOptions): Promise<void>;
    private executeRequest;
    private createRequest;
}
